[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufRead'
hook_source = '''
  lua require('lsp_rc')
'''

[[plugins]]
repo = 'kabouzeid/nvim-lspinstall'
on_source = 'nvim-lspconfig'
hook_source = '''
  lua require'lspinstall'.setup()
'''

[[plugins]]
repo = 'glepnir/lspsaga.nvim'
on_source='nvim-lspconfig'
hook_source = '''
nnoremap <silent> <leader>f :Lspsaga lsp_finder<CR>
nnoremap <silent><leader>ca :Lspsaga code_action<CR>
vnoremap <silent><leader>ca :<C-U>Lspsaga range_code_action<CR>
nnoremap <silent><leader>cd :Lspsaga hover_doc<CR>
nnoremap <silent> <leader>sig :Lspsaga signature_help<CR>
nnoremap <silent> <leader>rename :Lspsaga rename<CR>
nnoremap <silent> <leader>d :Lspsaga preview_definition<CR>
nnoremap <silent> <leader>e :Lspsaga show_line_diagnostics<CR>
nnoremap <silent> [e :Lspsaga diagnostic_jump_next<CR>
nnoremap <silent> ]e :Lspsaga diagnostic_jump_prev<CR>
highlight LspDiagnosticsSignError ctermbg=9 ctermfg=15
highlight LspDiagnosticsSignHint ctermbg=142 ctermfg=15
'''
