set number
set ruler
set wildmenu 
set list 
set listchars=tab:>-,trail:* 
set smartindent
set autoindent
set mouse=a
set nobackup
set clipboard=unnamedplus
set noswapfile

set expandtab
set tabstop=4
set shiftwidth=4

set fenc=utf-8
set encoding=utf-8
set hidden

let lisp_rainbow=1

filetype plugin on
filetype indent on

set noerrorbells

"Colorscheme読み込み時の背景の透過設定
augroup TransparentBG
  autocmd!
  autocmd Colorscheme * highlight Normal ctermbg=none "テキスト
  autocmd Colorscheme * highlight NonText ctermbg=none "テキスト下の余白
  autocmd Colorscheme * highlight LineNr ctermbg=none "行番号
  autocmd Colorscheme * highlight Folded ctermbg=none "コマンド折りたたみ
  autocmd Colorscheme * highlight EndOfBuffer ctermbg=none "ファイル終わり以降の空白
augroup END


"最後のカーソル位置の復元
if has("autocmd")
    autocmd BufReadPost *
    \ if line("'\"") > 0 && line ("'\"") <= line("$") |
    \   exe "normal! g'\"" |
    \ endif
endif

" 関数を定義
function Indent()
  let save_cursor = getcurpos()
  execute "normal " . "gg=G"
  call setpos('.', save_cursor)
endfunction
command -nargs=0 Indent call Indent()

"set visualbell

inoremap <silent> jj <ESC>
nnoremap <silent> <S-l> $
nnoremap <silent> <S-h> ^
nnoremap <silent> <S-k> {
nnoremap <silent> <S-j> }
nnoremap <silent> <C-h> B
nnoremap <silent> <C-l> W
nnoremap <silent> <C-k> 4k
nnoremap <silent> <C-j> 4j
nnoremap <silent> s "_s
nnoremap <silent> <C-Right> :bnext<CR>
nnoremap <silent> <C-Left> :bprev<CR>


if has('nvim')
  " Neovim specific commands------------------------------------------------

  "dein Scripts-----------------------------
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=/home/sagoj0_/.cache/dein/repos/github.com/Shougo/dein.vim

  " Required:
  if dein#load_state('/home/sagoj0_/.cache/dein')
    call dein#begin('/home/sagoj0_/.cache/dein')

    " Let dein manage dein
    " Required:
    "call dein#add('/home/sagoj0_/.cache/dein/repos/github.com/Shougo/dein.vim')
    
    let s:toml_file = '~/.config/nvim/dein.toml'
    let s:toml_lazy_file = fnamemodify(expand('<sfile>'), ':h').'/dein_lazy.toml'

    call dein#load_toml(s:toml_file, {'lazy': 0})
    call dein#load_toml(s:toml_lazy_file, {'lazy': 1})
    " Add or remove your plugins here like this:
    
  "  call dein#add('Shougo/neosnippet.vim')
  "  call dein#add('Shougo/neosnippet-snippets')

    " Required:
    call dein#end()
    call dein#save_state()
  endif

  " Required:
  filetype plugin indent on
  syntax enable

  " If you want to install not installed plugins on startup.
  if dein#check_install()
    call dein#install()
  endif

  "End dein Scripts-------------------------
  "set termguicolors
  set background=dark
  syntax on
  let g:lightline = {'colorscheme': 'candid' }
  colorscheme candid

endif
